In [2]:
import pandas as pd

In [3]:
data = pd.read_excel("ecommerce_orders_dataset.xlsx")

In [4]:
'''checking for data and eda'''

'checking for data and eda'

In [5]:
data.head(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,NaN,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [6]:
'''data understanding'''

'data understanding'

In [7]:
data.shape

(1200, 14)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

In [9]:
data.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [10]:
data.isna().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [11]:
data.duplicated().sum()

np.int64(0)

In [12]:
data.nunique()

OrderID            1200
Date                671
CustomerID         1189
Product               7
Quantity              5
UnitPrice          1193
ShippingAddress     655
PaymentMethod         5
OrderStatus           5
TrackingNumber     1200
ItemsInCart          10
CouponCode            3
ReferralSource        5
TotalPrice         1195
dtype: int64

In [13]:
'''eda'''

'eda'

In [14]:
data['OrderStatus'].value_counts()

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [15]:
data['Product'].value_counts()

Product
Printer    181
Tablet     179
Chair      178
Laptop     173
Desk       170
Monitor    163
Phone      156
Name: count, dtype: int64

In [16]:
data['PaymentMethod'].value_counts()

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64

In [17]:
data['ReferralSource'].value_counts()

ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64

In [18]:
data['CouponCode'].value_counts(dropna=False)

CouponCode
FREESHIP    313
NaN         309
WINTER15    292
SAVE10      286
Name: count, dtype: int64

In [19]:
data[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']].describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [20]:
data.groupby('OrderStatus')['TotalPrice'].agg(['count', 'sum', 'mean', 'median'])

             count        sum         mean  median
OrderStatus
Cancelled      250  276396.21  1105.584840  875.48
Delivered      231  242600.32  1050.217835  789.57
Pending        237  256328.15  1081.553376  869.80
Returned       247  243277.70   984.929960  754.44
Shipped        235  246159.58  1047.487574  816.64

In [21]:
data.groupby('Product')['TotalPrice'].agg(['count', 'sum', 'mean']).sort_values('sum', ascending=False)

         count        sum         mean
Product
Chair      178  195620.11  1098.989382
Printer    181  195612.61  1080.732652
Laptop     173  192126.56  1110.558150
Tablet     179  186568.95  1042.284637
Monitor    163  175651.41  1077.616012
Desk       170  167459.93   985.058412
Phone      156  151722.39   972.579423

In [22]:
data.groupby('PaymentMethod')['TotalPrice'].agg(['count', 'sum', 'mean'])

               count        sum         mean
PaymentMethod
Cash             246  259786.29  1056.041829
Credit Card      234  263847.63  1127.553974
Debit Card       232  232361.18  1001.556810
Gift Card        230  246323.92  1070.973565
Online           258  262442.94  1017.220698

In [23]:
data.groupby('ReferralSource')['TotalPrice'].agg(['count', 'sum', 'mean']).sort_values('sum', ascending=False)

                count        sum         mean
ReferralSource
Instagram         259  275285.45  1062.878185
Email             250  261808.55  1047.234200
Google            241  250441.48  1039.176266
Facebook          228  250410.90  1098.293421
Referral          222  226815.58  1021.691802

In [24]:
data['CouponUsed'] = data['CouponCode'].notna()
data.groupby('CouponUsed')['TotalPrice'].agg(['count', 'sum', 'mean', 'median'])

            count        sum         mean  median
CouponUsed
False         309  322401.41  1043.370259  834.12
True          891  942360.55  1057.643715  819.50

In [26]:
data[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']].corr()

             Quantity  UnitPrice  ItemsInCart  TotalPrice
Quantity     1.000000   0.014553     0.650061    0.615251
UnitPrice    0.014553   1.000000     0.000602    0.717081
ItemsInCart  0.650061   0.000602     1.000000    0.392540
TotalPrice   0.615251   0.717081     0.392540    1.000000

In [27]:
customer_orders = (
    data.groupby('CustomerID')['OrderID']
      .nunique()
)

In [28]:
customer_orders.value_counts().sort_index()

OrderID
1    1178
2      11
Name: count, dtype: int64

In [29]:
repeat_customers = (customer_orders > 1).sum()
total_customers = customer_orders.size

repeat_purchase_rate = repeat_customers / total_customers * 100

In [30]:
data['OrderStatus'].value_counts()

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

In [31]:
data['CouponUsed'] = data['CouponCode'].notna()

data.groupby('CouponUsed')['TotalPrice'].agg(
    ['count', 'sum', 'mean', 'median']
)

            count        sum         mean  median
CouponUsed
False         309  322401.41  1043.370259  834.12
True          891  942360.55  1057.643715  819.50

In [32]:
data.groupby('ReferralSource')['TotalPrice'].agg(
    ['count', 'sum', 'mean']
).sort_values('sum', ascending=False)

                count        sum         mean
ReferralSource
Instagram         259  275285.45  1062.878185
Email             250  261808.55  1047.234200
Google            241  250441.48  1039.176266
Facebook          228  250410.90  1098.293421
Referral          222  226815.58  1021.691802